// grid-packages/ag-grid-docs/documentation/doc-pages/component-cell-renderer/examples/dynamic-components/provided/modules/react/childMessageRenderer.jsx
import React, {Component} from "react";

export default class ChildMessageRenderer extends Component {
    constructor(props) {
        super(props);

        this.invokeParentMethod = this.invokeParentMethod.bind(this);
    }

    invokeParentMethod() {
        this.props.context.componentParent.methodFromParent(`Row: ${this.props.node.rowIndex}, Col: ${this.props.colDef.headerName}`)
    }

    render() {
        return (
            <span><button style={{height: 20, lineHeight: 0.5}} onClick={this.invokeParentMethod}
                          className="btn btn-info">Invoke Parent</button></span>
        );
    }
};

// documentation/ag-grid-docs/src/content/docs/component-cell-renderer/_examples/dynamic-components/provided/modules/angular/child-message-renderer.component.ts
import { Component } from '@angular/core';

import type { ICellRendererAngularComp } from 'ag-grid-angular';
import type { ICellRendererParams } from 'ag-grid-community';

@Component({
    standalone: true,
    selector: 'child-cell',
    template: `<span
        ><button style="height: 20px" (click)="invokeParentMethod()" class="btn btn-info">Invoke Parent</button></span
    >`,
    styles: [
        `
            .btn {
                line-height: 0.5;
            }
        `,
    ],
})
export class ChildMessageRenderer implements ICellRendererAngularComp {
    public params!: ICellRendererParams;

    agInit(params: ICellRendererParams): void {
        this.params = params;
    }

    public invokeParentMethod() {
        this.params.context.componentParent.methodFromParent(
            `Row: ${this.params.node.rowIndex}, Col: ${this.params.colDef?.headerName}`
        );
    }

    refresh(): boolean {
        return false;
    }
}
