// grid-packages/ag-grid-docs/documentation/doc-pages/component-filter/examples/filter-component/provided/modules/reactFunctionalTs/partialMatchFilter.tsx
import { IAfterGuiAttachedParams, IDoesFilterPassParams, IFilterParams } from '@ag-grid-community/core';
import React, { forwardRef, useEffect, useImperativeHandle, useRef, useState } from 'react';
import ReactDOM from 'react-dom';

export default forwardRef((props: IFilterParams, ref) => {
    const [text, setText] = useState('');
    const refInput = useRef(null);

    useEffect(() => {
        props.filterChangedCallback()
    }, [text])

    useImperativeHandle(ref, () => {
        return {
            isFilterActive() {
                return text != null && text !== '';
            },

            doesFilterPass(params: IDoesFilterPassParams) {
                const { node } = params;
                const value = props.getValue(node).toString().toLowerCase();

                return text.toLowerCase()
                    .split(' ')
                    .every(filterWord => value.indexOf(filterWord) >= 0);
            },

            getModel() {
                if (!this.isFilterActive()) { return null; }

                return { value: text };
            },

            setModel(model: any) {
                setText(model ? model.value : '');
            },

            afterGuiAttached(params: IAfterGuiAttachedParams) {
                focus();
            },

            componentMethod(message: string) {
                alert(`Alert from PartialMatchFilterComponent: ${message}`);
            }
        }
    });

    const focus = () => {
        window.setTimeout(() => {
            const container = ReactDOM.findDOMNode(refInput.current) as any;
            if (container) {
                container.focus();
            }
        });
    }

    const onChange = (event: any) => {
        const newValue = event.target.value;
        if (text !== newValue) {
            setText(newValue);
        }
    }

    const style = {
        borderRadius: '5px',
        backgroundColor: '#33CC3344',
        width: '200px',
        height: '50px'
    };

    return (
        <div style={style}>Filter:
            <input style={{ height: '20px' }} ref={refInput}
                value={text}
                onChange={onChange}
                className="form-control" />
        </div>
    );

});

// src/example-angular-filter/filter/app/partial-match-filter.component.ts
import {Component, ViewChild, ViewContainerRef} from "@angular/core";

import {IAfterGuiAttachedParams, IDoesFilterPassParams, IFilterParams, RowNode} from "ag-grid";
import {IFilterAngularComp} from "ag-grid-angular";

@Component({
    selector: 'filter-cell',
    template: `
        Filter: <input style="height: 20px" #input (ngModelChange)="onChange($event)" [ngModel]="text">
    `
})
export class PartialMatchFilterComponent implements IFilterAngularComp {
    private params: IFilterParams;
    private valueGetter: (rowNode: RowNode) => any;
    public text: string = '';

    @ViewChild('input', {read: ViewContainerRef}) public input;

    agInit(params: IFilterParams): void {
        this.params = params;
        this.valueGetter = params.valueGetter;
    }

    isFilterActive(): boolean {
        return this.text !== null && this.text !== undefined && this.text !== '';
    }

    doesFilterPass(params: IDoesFilterPassParams): boolean {
        return this.text.toLowerCase()
            .split(" ")
            .every((filterWord) => {
                return this.valueGetter(params.node).toString().toLowerCase().indexOf(filterWord) >= 0;
            });
    }

    getModel(): any {
        return {value: this.text};
    }

    setModel(model: any): void {
        this.text = model ? model.value : '';
    }

    afterGuiAttached(params: IAfterGuiAttachedParams): void {
        this.input.element.nativeElement.focus();
    }

    componentMethod(message: string): void {
        alert(`Alert from PartialMatchFilterComponent ${message}`);
    }

    onChange(newValue): void {
        if (this.text !== newValue) {
            this.text = newValue;
            this.params.filterChangedCallback();
        }
    }
}
