// documentation/ag-grid-docs/src/content/docs/theming/_examples/basic/provided/modules/angular/app.component.ts
import { AgGridAngular } from '@ag-grid-community/angular';
import { ClientSideRowModelModule } from '@ag-grid-community/client-side-row-model';
import type { ColDef } from '@ag-grid-community/core';
import { ModuleRegistry } from '@ag-grid-community/core';
import { themeQuartz } from '@ag-grid-community/theming';
import { Component } from '@angular/core';

ModuleRegistry.registerModules([ClientSideRowModelModule]);

@Component({
    standalone: true,
    imports: [AgGridAngular],
    selector: 'my-app',
    template: `
        <ag-grid-angular
            style="height: 100%;"
            loadThemeGoogleFonts
            [columnDefs]="columnDefs"
            [defaultColDef]="defaultColDef"
            [rowData]="rowData"
            [theme]="theme"
        />
    `,
})
export class AppComponent {
    theme = themeQuartz;

    columnDefs: ColDef[] = [{ field: 'make' }, { field: 'model' }, { field: 'price' }];

    defaultColDef: ColDef = {
        editable: true,
        flex: 1,
        minWidth: 100,
        filter: true,
    };

    rowData: any[] = (() => {
        const rowData: any[] = [];
        for (let i = 0; i < 10; i++) {
            rowData.push({ make: 'Toyota', model: 'Celica', price: 35000 + i * 1000 });
            rowData.push({ make: 'Ford', model: 'Mondeo', price: 32000 + i * 1000 });
            rowData.push({ make: 'Porsche', model: 'Boxster', price: 72000 + i * 1000 });
        }
        return rowData;
    })();
}

// grid-community-modules/solid/dev/App.tsx
import type {Component} from "solid-js";
import AgGridSolid from "../src";
import {ClientSideRowModelModule} from '@ag-grid-community/client-side-row-model';

import '@ag-grid-community/styles/ag-grid.css';
import '@ag-grid-community/styles/ag-theme-quartz.css';
import { ColDef } from "@ag-grid-community/core";

interface ICar {
    make: string;
    model: string;
    price: number;
}

const App: Component = () => {
    const columnDefs: ColDef<ICar>[] = [
        {field: "make"},
        {field: "model"},
        {field: "price"},
    ];

    const rowData : ICar[] = [
        {make: "Toyota", model: "Celica", price: 35000},
        {make: "Ford", model: "Mondeo", price: 32000},
        {make: "Porsche", model: "Boxster", price: 72000}
    ];

    const defaultColDef = {
        flex: 1,
        floatingFilter: true,
        filter: true,
    };

    return (
        <div class="ag-theme-quartz" style={{height: "100%"}}>
            <AgGridSolid
                columnDefs={columnDefs}
                rowData={rowData}
                defaultColDef={defaultColDef}
                modules={[ClientSideRowModelModule]}
            />
        </div>
    );
};

export default App;
