// grid-packages/ag-grid-docs/documentation/doc-pages/component-cell-renderer/examples/dynamic-components/provided/packages/angular/app/currency-renderer.component.ts
import {Component} from "@angular/core";

import {ICellRendererAngularComp} from "ag-grid-angular";

@Component({
    selector: 'currency-cell',
    template: `{{params.value | currency:'EUR'}}`
})
export class CurrencyRenderer implements ICellRendererAngularComp {
    public params: any;

    agInit(params: any): void {
        this.params = params;
    }

    refresh(): boolean {
        return false;
    }
}

// grid-packages/ag-grid-docs/src/javascript-grid-cell-rendering-components/dynamic-components/currencyRenderer_react.jsx
import React, {Component} from "react";

export default class CurrencyRenderer extends Component {
    constructor(props) {
        super(props);

        this.state = {
            value: props.value
        }
    }

    formatValueToCurrency(currency, value) {
        return `${currency}${value.toFixed(2)}`
    }

    // noinspection JSUnusedGlobalSymbols
    refresh(params) {
        if(params.value !== this.state.value) {
            this.setState({
                value: params.value
            })
        }
        return true;
    }

    render() {
        return (
            <span>{this.formatValueToCurrency('EUR', this.state.value)}</span>
        );
    }
};
