// grid-packages/ag-grid-solid/dev/App.tsx
import type { Component } from "solid-js";
import AgGridSolid from "../src";

import "@ag-grid-community/styles/ag-grid.css";
import "@ag-grid-community/styles/ag-theme-alpine.css";

const App: Component = () => {
  const columnDefs = [{ field: "make" }, { field: "model" }, { field: "price" }];

  const rowData = [
    { make: "Toyota", model: "Celica", price: 35000 },
    { make: "Ford", model: "Mondeo", price: 32000 },
    { make: "Porsche", model: "Boxster", price: 72000 },
  ];

  const defaultColDef = {
    flex: 1,
  };

  return (
    <div class="ag-theme-alpine" style={{ height: "100%" }}>
      <AgGridSolid columnDefs={columnDefs} rowData={rowData} defaultColDef={defaultColDef} />
    </div>
  );
};

export default App;

// examples-grid/ag-grid-vue-webpack/src/App.vue
<template>
  <ag-grid-vue
          style="width: 500px; height: 200px"
          class="ag-theme-alpine"
          :columnDefs="columnDefs"
          :rowData="rowData"
  >
  </ag-grid-vue>
</template>

<script>
  import "ag-grid-community/dist/styles/ag-grid.css";
  import "ag-grid-community/dist/styles/ag-theme-alpine.css";
  import { AgGridVue } from "ag-grid-vue";

  export default {
    name: "App",
    data() {
      return {
        columnDefs: null,
        rowData: null,
      };
    },
    components: {
      AgGridVue,
    },
    beforeMount() {
      this.columnDefs = [
        { field: "make" },
        { field: "model" },
        { field: "price" },
      ];

      this.rowData = [
        { make: "Toyota", model: "Celica", price: 35000 },
        { make: "Ford", model: "Mondeo", price: 32000 },
        { make: "Porsche", model: "Boxter", price: 72000 },
      ];
    },
  };
</script>
