// examples-grid/ag-grid-vue-example-legacy/src/rich-grid-example/DateComponent.vue
<template>
    <div class="filter">
        <span class="reset" @click="onResetDate()">x</span>
        <input class="dd" @change="onDateChanged('dd', $event)" placeholder="dd" v-model="dd"
               maxLength="2"/>/
        <input class="mm" @change="onDateChanged('mm', $event)" placeholder="mm" v-model="mm"
               maxLength="2"/>/
        <input class="yyyy" @change="onDateChanged('yyyy', $event)" placeholder="yyyy" v-model="yyyy"
               maxLength="4"/>
    </div>
</template>

<script>
    import Vue from "vue";

    export default Vue.extend({
        data() {
            return {
                date: null,
                dd: '',
                mm: '',
                yyyy: ''
            }
        },
        methods: {
            onResetDate() {
                this.dd = '';
                this.mm = '';
                this.yyyy = '';
                this.date = null;
                this.params.onDateChanged();
            },

            onDateChanged(on, $event) {
                let targetValue = $event.target.value;
                this.date = this.parseDate(
                    on === 'dd' ? targetValue : this.dd,
                    on === 'mm' ? targetValue : this.mm,
                    on === 'yyyy' ? targetValue : this.yyyy
                );
                this.params.onDateChanged();
            },

            getDate() {
                return this.date;
            },

            setDate(date) {
                if (!date) return;

                this.dd = date.getDate() + '';
                this.mm = (date.getMonth() + 1) + '';
                this.yyyy = date.getFullYear() + '';
                this.date = date;
                this.params.onDateChanged();
            },

            parseDate(dd, mm, yyyy) {
                //If any of the three input date fields are empty, stop and return null
                if (dd.trim() === '' || mm.trim() === '' || yyyy.trim() === '') {
                    return null;
                }

                let day = Number(dd);
                let month = Number(mm);
                let year = Number(yyyy);

                let date = new Date(year, month - 1, day);

                //If the date is not valid
                if (isNaN(date.getTime())) {
                    return null;
                }

                if (date.getDate() != day || date.getMonth() + 1 != month || date.getFullYear() != year) {
                    return null;
                }
                return date;
            }
        }
    })

</script>

<style scoped>
    .filter {
        margin: 2px
    }

    .dd {
        width: 30px
    }

    .mm {
        width: 30px
    }

    .yyyy {
        width: 60px
    }

    .reset {
        padding: 2px;
        background-color: red;
        border-radius: 3px;
        font-size: 10px;
        margin-right: 5px;
        color: white
    }
</style>

// src/example-angular-rich-grid/rich-grid-example/app/date-component/date.component.ts
import {Component} from "@angular/core";
import {IDateParams} from "ag-grid/main";
import {IDateAngularComp} from "ag-grid-angular/main";


@Component({
    selector: 'ag-date-component',
    templateUrl: './date.component.html',
    styles: [`
        .dd {
            width: 30px
        }
        
        .mm {
            width: 30px
        }
        
        .yyyy {
            width: 40px
        }
        
        .reset {
            padding: 2px;
            background-color: red;
            border-radius: 3px;
            font-size: 10px;
            color: white
        }
    `]
})
export class DateComponent implements IDateAngularComp {
    private date: Date;
    private params: IDateParams;
    public dd: string = '';
    public mm: string = '';
    public yyyy: string = '';

    agInit(params: IDateParams): void {
        this.params = params;
    }

    ngOnDestroy() {
        console.log(`Destroying DateComponent`);
    }

    // when the date filter X is clicked on the date fields clear as expected, but the filter doesn't update
    // how should this work? todo alboert
    onResetDate() {
        this.dd = '';
        this.mm = '';
        this.yyyy = '';
        this.date = null;
        this.params.onDateChanged();
    }

    onDateChanged(on: string, newValue: string) {
        this.date = this.parseDate(
            on === 'dd' ? newValue : this.dd,
            on === 'mm' ? newValue : this.mm,
            on === 'yyyy' ? newValue : this.yyyy
        );
        this.params.onDateChanged();
    }

    getDate(): Date {
        return this.date;
    }

    setDate(date: Date): void {
        if (date == null) {
            // this doesn't work - the associated date filter will throw an error as the date will be null
            // test case: expand employee then click refresh data
            // what do we do here? todo alberto
            // this.onResetDate();
        } else {
            this.dd = date.getDate() + '';
            this.mm = (date.getMonth() + 1) + '';
            this.yyyy = date.getFullYear() + '';
            this.date = date;
            this.params.onDateChanged();
        }
    }

    //*********************************************************************************
    //          INTERNAL LOGIC
    //*********************************************************************************

    parseDate(dd, mm, yyyy) {
        //If any of the three input date fields are empty, stop and return null
        if (dd.trim() === '' || mm.trim() === '' || yyyy.trim() === '') {
            return null;
        }

        let day = Number(dd);
        let month = Number(mm);
        let year = Number(yyyy);

        let date = new Date(year, month - 1, day);

        //If the date is not valid
        if (isNaN(date.getTime())) {
            return null;
        }

        //Given that new Date takes any garbage in, it is possible for the user to specify a new Date
        //like this (-1, 35, 1) and it will return a valid javascript date. In this example, it will
        //return Sat Dec 01    1 00:00:00 GMT+0000 (GMT) - Go figure...
        //To ensure that we are not letting non sensical dates to go through we check that the resultant
        //javascript date parts (month, year and day) match the given date fields provided as parameters.
        //If the javascript date parts don't match the provided fields, we assume that the input is non
        //sensical... ie: Day=-1 or month=14, if this is the case, we return null
        //This also protects us from non sensical dates like dd=31, mm=2 of any year
        if (date.getDate() != day || date.getMonth() + 1 != month || date.getFullYear() != year) {
            return null;
        }

        return date;
    }
}
