// grid-packages/ag-grid-docs/documentation/doc-pages/component-cell-renderer/examples/cell-renderer/provided/modules/reactFunctional/daysFrostRenderer.jsx
import React from 'react';

export default props => (
    <span>
        {
            new Array(props.value).fill('')
                .map(ignore =>
                    (<img src={`https://www.ag-grid.com/example-assets/weather/${props.rendererImage}`}/>)
                )
        }
    </span>
);

// grid-packages/ag-grid-docs/documentation/doc-pages/component-cell-renderer/examples/cell-renderer/provided/modules/angular/app/days-frost-renderer.component.ts
import {Component} from "@angular/core";

@Component({
    selector: 'day-component',
    template: `<span><img *ngFor="let number of value" [src]="rendererImage"/></span>`
})
export class DaysFrostRenderer {
    params: any;
    rendererImage: string;
    value: any[];

    agInit(params: any): void {
        this.params = params;
        this.updateImage();
    }

    updateImage() {
        this.rendererImage = `https://www.ag-grid.com/example-assets/weather/${this.params.rendererImage}`;
        this.value = new Array(this.params.value).fill(0);
    }

    refresh(params: any) {
        this.params = params;
        this.updateImage();
    }
}
