// old-src/javascript-grid-cell-editor/angular-editor/app/mood-renderer.component.ts
import {Component} from "@angular/core";

import {ICellRendererAngularComp} from "ag-grid-angular";

@Component({
    selector: 'mood-cell',
    template: `<img width="20px" [src]="imgForMood"/>`
})
export class MoodRendererComponent implements ICellRendererAngularComp {
    private params: any;
    private mood: string;
    public imgForMood: string;

    agInit(params: any): void {
        this.params = params;
        this.setMood(params);
    }

    refresh(params: any): boolean {
        this.params = params;
        this.setMood(params);
        return true;
    }

    private setMood(params) {
        this.mood = params.value;
        this.imgForMood = this.mood === 'Happy' ? 'https://www.ag-grid.com/images/smiley.png' : 'https://www.ag-grid.com/images/smiley-sad.png';
    };
}

// grid-packages/ag-grid-docs/documentation/doc-pages/cell-rendering/examples/dynamic-rendering-component/moodRenderer_react.jsx
import React, { Component } from 'react';

export default class MoodRenderer extends Component {
    constructor(props) {
        super(props);
    }

    componentWillMount() {
        this.setMood(this.props.value);
    }

    refresh(params) {
        this.setMood(params.value);
    }

    setMood(mood) {
        this.setState({
            imgForMood: 'https://www.ag-grid.com/example-assets/smileys/' + (mood === 'Happy' ? 'happy.png' : 'sad.png')
        });
    };

    render() {
        return (
            <img width="20px" src={this.state.imgForMood} />
        );
    }
}
