// old-src/javascript-grid-floating-filter-component/angular-floating/app/slider-floating-filter.component.ts
import {AfterViewInit, Component} from "@angular/core";

import {IFloatingFilter, IFloatingFilterParams, SerializedNumberFilter} from "ag-grid";
import {AgFrameworkComponent} from "ag-grid-angular";

export interface SliderFloatingFilterChange {
    model: SerializedNumberFilter
}

export interface SliderFloatingFilterParams extends IFloatingFilterParams<SerializedNumberFilter, SliderFloatingFilterChange> {
    value: number
    maxValue: number
}

@Component({
    template: `
        <input type="range" 
               min="0" [max]="maxValue"
               data-show-value="true" data-popup-enabled="true"
               [(ngModel)]="currentValue"
               (ngModelChange)="valueChanged()"/>`
})
export class SliderFloatingFilter implements IFloatingFilter<SerializedNumberFilter, SliderFloatingFilterChange, SliderFloatingFilterParams>, AgFrameworkComponent<SliderFloatingFilterParams>, AfterViewInit {
    private params: SliderFloatingFilterParams;
    public maxValue: number;
    public currentValue: number;

    agInit(params: SliderFloatingFilterParams): void {
        this.params = params;
        this.maxValue = this.params.maxValue;
        this.currentValue = 0;
    }

    valueChanged() {
        this.params.onFloatingFilterChanged({model: this.buildModel()});
    }

    ngAfterViewInit(): void {
        this.valueChanged();
    }

    onParentModelChanged(parentModel: SerializedNumberFilter): void {
        if (!parentModel) {
            this.currentValue = 0;
        } else {
            // note that the filter could be anything here, but our purposes we're assuming a greater than filter only,
            // so just read off the value and use that
            this.currentValue = parentModel.filter
        }
    }

    buildModel(): SerializedNumberFilter {
        if (this.currentValue === 0) {
            return null;
        }
        return {
            filterType: 'number',
            type: 'greaterThan',
            filter: this.currentValue,
            filterTo: null
        };
    }

}

// packages/ag-grid-docs/src/javascript-grid-floating-filter-component/floating-filter-component/sliderFloatingFilter_react.jsx
import React, {Component} from "react";

export default class SliderFloatingFilter extends Component {
    constructor(props) {
        super(props);

        this.state = {
            maxValue: props.maxValue,
            currentValue: 0
        }
    }

    valueChanged = (event) => {
        this.setState({
                currentValue: event.target.value
            },
            () => {
                let valueToUse = (this.state.currentValue === 0) ? null : this.state.currentValue;
                this.props.parentFilterInstance( function(instance) {
                    instance.onFloatingFilterChanged('greaterThan', valueToUse);
                });
            })

    };

    onParentModelChanged(parentModel) {
        // note that the filter could be anything here, but our purposes we're assuming a greater than filter only,
        // so just read off the value and use that
        this.setState({
            currentValue: !parentModel ? 0 : parentModel.filter
        });
    }

    render() {
        return (
            <input type="range"
                   value={this.state.currentValue}
                   min={0}
                   max={this.state.maxValue}
                   step={1}
                   onChange={this.valueChanged}/>
        )
    }
}
