// grid-packages/ag-grid-docs/documentation/doc-pages/component-cell-renderer/examples/cell-renderer/provided/modules/reactFunctionalTs/daysFrostRenderer.tsx
import { ICellRendererParams } from '@ag-grid-community/core';
import React from 'react';

export interface ImageCellRendererParams extends ICellRendererParams {
    rendererImage: string
}

export default (props: ImageCellRendererParams) => (
    <span>
        {
            new Array(props.value).fill('')
                .map(ignore =>
                    (<img src={`https://www.ag-grid.com/example-assets/weather/${props.rendererImage}`} />)
                )
        }
    </span>
);

// grid-packages/ag-grid-docs/documentation/doc-pages/component-cell-renderer/examples/cell-renderer/provided/packages/angular/app/days-frost-renderer.component.ts
import { Component } from "@angular/core";

import { ICellRendererAngularComp } from "ag-grid-angular";
import { ICellRendererParams } from "ag-grid-community";

@Component({
    selector: 'day-component',
    template: `<span><img *ngFor="let number of value" [src]="rendererImage"/></span>`
})
export class DaysFrostRenderer implements ICellRendererAngularComp {
    params!: ICellRendererParams & { rendererImage: string };
    rendererImage!: string;
    value!: any[];

    agInit(params: ICellRendererParams & { rendererImage: string }): void {
        this.params = params;
        this.updateImage();
    }

    updateImage() {
        this.rendererImage = `https://www.ag-grid.com/example-assets/weather/${this.params.rendererImage}`;
        this.value = new Array(this.params.value).fill(0);
    }

    refresh(params: ICellRendererParams & { rendererImage: string }) {
        this.params = params;
        this.updateImage();
        return true
    }
}
