// src/example-react-master-detail/master-detail/DetailPanelComponent.jsx
import React, {Component} from "react";

import {AgGridReact} from "ag-grid-react";

export default class DetailPanelComponent extends Component {
    constructor(props) {
        super(props);

        this.state = {
            columnDefs: this.createColumnDefs(),
            parentRecord: this.props.node.parent.data,
            img: `https://www.ag-grid.com/images/${this.props.node.parent.data.image}.png`
        };

        this.onGridReady = this.onGridReady.bind(this);
        this.onSearchTextChange = this.onSearchTextChange.bind(this);

        // override the containing div so that the child grid fills the row height
        this.props.reactContainer.style.height = "100%";
    }

    onGridReady(params) {
        this.gridApi = params.api;
        this.columnApi = params.columnApi;

        this.gridApi.setRowData(this.state.parentRecord.callRecords);
        setTimeout(() => {
            this.gridApi.sizeColumnsToFit();
        })
    }

    onSearchTextChange(newData) {
        this.gridApi.setQuickFilter(newData);
    }

    createColumnDefs() {
        return [
            {headerName: 'Call ID', field: 'callId', cellClass: 'call-record-cell'},
            {headerName: 'Direction', field: 'direction', cellClass: 'call-record-cell'},
            {headerName: 'Number', field: 'number', cellClass: 'call-record-cell'},
            {
                headerName: 'Duration',
                field: 'duration',
                cellClass: 'call-record-cell',
                valueFormatter: this.secondCellFormatter
            },
            {headerName: 'Switch', field: 'switchCode', cellClass: 'call-record-cell'}];

    }

    secondCellFormatter(params) {
        return params.value.toLocaleString() + 's';
    }

    onButtonClick() {
        window.alert('Sample button pressed!!');
    }

    render() {
        return (
            <div className="full-width-panel">
                <div className="full-width-details">
                    <div className="full-width-detail"><img width="120px" src={this.state.img}/>
                    </div>
                    <div className="full-width-detail"><b>Name: </b> {this.state.parentRecord.name}</div>
                    <div className="full-width-detail"><b>Account: </b> {this.state.parentRecord.account}</div>
                </div>
                <AgGridReact
                    // properties
                    columnDefs={this.state.columnDefs}

                    enableSorting
                    enableFilter
                    enableColResize

                    // events
                    onGridReady={this.onGridReady}>
                </AgGridReact>
            </div>
        );
    }
}

// src/example-angular-master-detail/master-detail/app/master-detail-example/detail-panel.component.ts
import {AfterViewInit, Component} from "@angular/core";
import {GridOptions} from "ag-grid/main";
import {ICellRendererAngularComp} from "ag-grid-angular/main";

@Component({
    selector: 'ag-full-width-grid',
    templateUrl: './detail-panel.component.html',
    styleUrls: ['./detail-panel.component.css'],
})
export class DetailPanelComponent implements ICellRendererAngularComp, AfterViewInit {
    public gridOptions: GridOptions;
    public parentRecord: any;

    constructor() {
        this.gridOptions = <GridOptions>{};
        this.gridOptions.enableSorting = true;
        this.gridOptions.enableFilter = true;
        this.gridOptions.enableColResize = true;
        this.gridOptions.columnDefs = this.createColumnDefs();
    }

    agInit(params: any): void {
        this.parentRecord = params.node.parent.data;
    }

    // Sometimes the gridReady event can fire before the angular component is ready to receive it, so in an angular
    // environment its safer to on you cannot safely rely on AfterViewInit instead before using the API
    ngAfterViewInit() {
        this.gridOptions.api.setRowData(this.parentRecord.callRecords);
        this.gridOptions.api.sizeColumnsToFit();
    }

    onSearchTextChange(newData: string) {
        this.gridOptions.api.setQuickFilter(newData);
    }

    private createColumnDefs() {
        return [{headerName: 'Call ID', field: 'callId', cellClass: 'call-record-cell'},
            {headerName: 'Direction', field: 'direction', cellClass: 'call-record-cell'},
            {headerName: 'Number', field: 'number', cellClass: 'call-record-cell'},
            {
                headerName: 'Duration',
                field: 'duration',
                cellClass: 'call-record-cell',
                valueFormatter: this.secondCellFormatter
            },
            {headerName: 'Switch', field: 'switchCode', cellClass: 'call-record-cell'}];

    }

    private secondCellFormatter(params) {
        return params.value.toLocaleString() + 's';
    };

    // if we don't do this, then the mouse wheel will be picked up by the main
    // grid and scroll the main grid and not this component. this ensures that
    // the wheel move is only picked up by the text field
    consumeMouseWheelOnDetailGrid($event) {
        $event.stopPropagation();
    }

    onButtonClick() {
        window.alert('Sample button pressed!!');
    }

    refresh(): boolean {
        return false;
    }
}
<div class="full-width-panel">
    <div class="full-width-details">
        <div class="full-width-detail"><img width="120px" src="https://www.ag-grid.com/images/{{parentRecord.image}}.png"/></div>
        <div class="full-width-detail"><b>Name: </b> {{parentRecord.name}}</div>
        <div class="full-width-detail"><b>Account: </b> {{parentRecord.account}}</div>
    </div>
    <ag-grid-angular
            class="full-width-grid"
            [gridOptions]="gridOptions"

            enableSorting
            enableFilter
            enableColResize

            (mousewheel)="consumeMouseWheelOnDetailGrid($event)"
            (DOMMouseScroll)="consumeMouseWheelOnDetailGrid($event)">
    </ag-grid-angular>
    <div class="full-width-grid-toolbar">
        <img class="full-width-phone-icon" src="https://www.ag-grid.com/images/phone.png"/>
        <button (click)="onButtonClick()"><img src="https://www.ag-grid.com/images/fire.png"/></button>
        <button (click)="onButtonClick()"><img src="https://www.ag-grid.com/images/frost.png"/></button>
        <button (click)="onButtonClick()"><img src="https://www.ag-grid.com/images/sun.png"/></button>
        <input class="full-width-search" #box (keyup)="onSearchTextChange(box.value)" placeholder="Search..."/>
    </div>
</div>
