// documentation/ag-grid-docs/src/content/docs/cell-editors/_examples/get-editor-instance/provided/modules/angular/mySimple-editor.component.ts
import { ICellEditorAngularComp } from '@ag-grid-community/angular';
import { ICellEditorParams } from '@ag-grid-community/core';
import { AfterViewInit, Component, ViewChild, ViewContainerRef } from '@angular/core';

// backspace starts the editor on Windows
const KEY_BACKSPACE = 'Backspace';

@Component({
    standalone: true,
    template: `<input class="my-simple-editor" [value]="value" #input /> `,
})
export class MySimpleEditor implements ICellEditorAngularComp, AfterViewInit {
    private params!: ICellEditorParams;
    public value: any;

    @ViewChild('input', { read: ViewContainerRef }) public input!: ViewContainerRef;

    agInit(params: ICellEditorParams): void {
        this.params = params;

        this.value = this.getInitialValue(params);
    }

    getValue(): any {
        return this.value;
    }

    getInitialValue(params: ICellEditorParams): any {
        let startValue = params.value;

        const eventKey = params.eventKey;
        const isBackspace = eventKey === KEY_BACKSPACE;

        if (isBackspace) {
            startValue = '';
        } else if (eventKey && eventKey.length === 1) {
            startValue = eventKey;
        }

        if (startValue !== null && startValue !== undefined) {
            return startValue;
        }

        return '';
    }

    myCustomFunction() {
        return {
            rowIndex: this.params.rowIndex,
            colId: this.params.column.getId(),
        };
    }

    ngAfterViewInit() {
        setTimeout(() => {
            this.input.element.nativeElement.focus();
        });
    }
}

// grid-packages/ag-grid-docs/documentation/doc-pages/component-cell-editor/examples/get-editor-instance/provided/modules/react/mySimpleEditor.jsx
import React, {Component, createRef} from 'react';

// backspace starts the editor on Windows
const KEY_BACKSPACE = 'Backspace';

export default class MySimpleEditor extends Component {
    constructor(props) {
        super(props);

        this.inputRef = createRef();

        this.state = {
            value: this.getInitialValue(props)
        };
    }

    componentDidMount() {
        setTimeout(() => this.inputRef.current.focus())
    }

    getInitialValue(props) {
        let startValue = props.value;

        const eventKey = props.eventKey;
        const isBackspace = eventKey === KEY_BACKSPACE;

        if (isBackspace) {
            startValue = '';
        } else if (eventKey && eventKey.length === 1) {
            startValue = eventKey;
        }

        if (startValue !== null && startValue !== undefined) {
            return startValue;
        }

        return '';
    }

    getValue() {
        return this.state.value;
    }

    myCustomFunction() {
        return {
            rowIndex: this.props.rowIndex,
            colId: this.props.column.getId()
        };
    }

    render() {
        return (
            <input value={this.state.value} ref={this.inputRef}
                   onChange={event => this.setState({value: event.target.value})}
                   className="my-simple-editor" />
        );
    }
}
