// grid-packages/ag-grid-docs/documentation/doc-pages/component-cell-renderer/examples/cell-renderer/provided/modules/angular/app/days-frost-renderer.component.ts
import {Component} from "@angular/core";

@Component({
    selector: 'day-component',
    template: `<span><img *ngFor="let number of value" [src]="rendererImage"/></span>`
})
export class DaysFrostRenderer {
    params: any;
    rendererImage: string;
    value: any[];

    agInit(params: any): void {
        this.params = params;
        this.updateImage();
    }

    updateImage() {
        this.rendererImage = `https://www.ag-grid.com/example-assets/weather/${this.params.rendererImage}`;
        this.value = new Array(this.params.value).fill(0);
    }

    refresh(params: any) {
        this.params = params;
        this.updateImage();
    }
}

// grid-packages/ag-grid-docs/documentation/doc-pages/component-cell-renderer/examples/cell-renderer/provided/packages/react/daysFrostRenderer.jsx
import React, {Component} from "react";

export default class DaysFrostRenderer extends Component {
    constructor(props) {
        super(props);

        this.state = this.getImageState();
    }

    getImageState() {
        return {
            rendererImage: `https://www.ag-grid.com/example-assets/weather/${this.props.rendererImage}`
        }
    }

    render() {
        return (
            <span>{new Array(this.props.value).fill('').map(ignore =>
                (<img src={this.state.rendererImage} />)
            )}</span>
        );
    }
};
