// documentation/ag-grid-docs/src/content/docs/overlays-active/_examples/active-overlay-component/provided/angular/custom-overlay.component.ts
import { Component, signal } from '@angular/core';

import type { IOverlayAngularComp } from 'ag-grid-angular';
import type { IOverlayParams } from 'ag-grid-community';

export interface CustomParams {
    count: number;
}

@Component({
    selector: 'app-custom-overlay',
    standalone: true,
    template: `<div class="my-custom-overlay">
        <span>Custom Overlay: {{ count() }}</span>
        <span class="visually-hidden" role="status" aria-live="polite" aria-atomic="true">
            Custom overlay shown. Count {{ count() }}.
        </span>
    </div>`,
})
export class CustomOverlayComponent implements IOverlayAngularComp {
    public count = signal(0);

    public agInit(params: IOverlayParams & CustomParams): void {
        this.refresh(params);
    }

    public refresh(params: IOverlayParams & CustomParams): void {
        this.count.set(params.count);
    }
}

// documentation/ag-grid-docs/src/content/docs/overlays-active/_examples/active-overlay-component/provided/reactFunctionalTs/customOverlay.tsx
import React from 'react';

import type { CustomOverlayProps } from 'ag-grid-react';

export interface CustomParams {
    count: number;
}

export const CustomOverlay = (props: CustomOverlayProps & CustomParams) => {
    const statusText = `Custom overlay shown. Count ${props.count}.`;

    return (
        <div className="my-custom-overlay">
            <span>Custom Overlay: {props.count}</span>
            <span className="visually-hidden" role="status" aria-live="polite" aria-atomic="true">
                {statusText}
            </span>
        </div>
    );
};
