// src/react-examples/examples/src/groupedRowInnerRendererExample/MedalRenderer.jsx
import React, {Component} from "react";

export default class MedalRenderer extends Component {
    constructor(props) {
        super(props);

        this.country = this.props.node.key;
        this.gold = this.props.data.gold;
        this.silver = this.props.data.silver;
        this.bronze = this.props.data.bronze;
    }

    render() {
        return (
            <span>{this.country} Gold: {this.gold}, Silver: {this.silver}, Bronze: {this.bronze}</span>
        );
    }
};

// src/ng2-example/app/grouped-row-example/medal-renderer.component.ts
import {Component} from '@angular/core';

import {ICellRendererAngularComp} from 'ag-grid-angular/main';

@Component({
    selector: 'group-row-cell',
    template: `{{country}} Gold: {{gold}}, Silver: {{silver}}, Bronze: {{bronze}}`
})
export class MedalRendererComponent implements ICellRendererAngularComp {
    private params: any;
    public country: string;
    public gold: string;
    public silver: string;
    public bronze: string;

    agInit(params: any): void {
        this.params = params;
        this.country = params.node.key;
        this.gold = params.data.gold;
        this.silver = params.data.silver;
        this.bronze = params.data.bronze;
    }
}
