// documentation/ag-grid-docs/src/content/docs/rtl/_examples/rtl-complex/provided/angular/country-cell-renderer.component.ts
import { Component, signal } from '@angular/core';

import type { ICellRendererAngularComp } from 'ag-grid-angular';
import type { ICellRendererParams } from 'ag-grid-community';

@Component({
    standalone: true,
    template: `<span style="cursor: default; overflow: hidden; text-overflow: ellipsis">
        @if (flagCode()) {
            <img
                class="flag"
                border="0"
                width="15"
                height="10"
                src="https://flags.fmcdn.net/data/flags/mini/{{ flagCode() }}.png"
            />
        }
        {{ textValue() }}
    </span>`,
})
export class CountryCellRenderer implements ICellRendererAngularComp {
    public readonly textValue = signal<string | undefined>(undefined);
    public readonly flagCode = signal<string | undefined>(undefined);

    public agInit(params: ICellRendererParams): void {
        this.flagCode.set(undefined);

        const value = params.value;
        // Blank, empty or the set-filter "Select All" entry: show the raw value with no flag.
        if (value == null || value === '' || value === '(Select All)') {
            this.textValue.set(value);
            return;
        }

        // Only render a flag when a country code resolves; the localised Arabic/Hebrew names have no
        // entry in COUNTRY_CODES, so guarding here avoids requesting undefined.png (404s).
        const code = params.context.COUNTRY_CODES[value];
        if (code) {
            this.flagCode.set(code);
        }
        this.textValue.set(value);
    }

    public refresh(): boolean {
        return false;
    }
}

// documentation/ag-grid-docs/src/content/docs/rtl/_examples/rtl-complex/provided/reactFunctionalTs/countryCellRenderer.tsx
import React from 'react';

import type { CustomCellRendererProps } from 'ag-grid-react';

const spanStyle: React.CSSProperties = {
    cursor: 'default',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
};

// React port of the frozen `country-renderer_typescript.ts`. Reads the shared flag lookup from
// `props.context.COUNTRY_CODES`. Only renders the flag `<img>` when a code resolves for the value;
// blank/`(Select All)` values and unmapped (localised Arabic/Hebrew) country names render as plain
// text, which avoids requesting `undefined.png` and the resulting 404s in RTL mode.
export default (props: CustomCellRendererProps) => {
    const value = props.value;

    if (value == null || value === '' || value === '(Select All)') {
        return <span style={spanStyle}>{value}</span>;
    }

    const code: string | undefined = props.context.COUNTRY_CODES[value];
    if (code) {
        return (
            <span style={spanStyle}>
                <img
                    className="flag"
                    width={15}
                    height={10}
                    src={`https://flags.fmcdn.net/data/flags/mini/${code}.png`}
                />{' '}
                {value}
            </span>
        );
    }

    return <span style={spanStyle}>{value}</span>;
};
