// grid-packages/ag-grid-docs/documentation/src/pages/column-updating-definitions/examples/refresh-headers/customHeader_react.jsx
import React, { Component } from 'react';

export default class CustomHeader extends Component {
    render() {
        return (
            <div style={{ display: 'flex' }}>
                {this.props.enableMenu && <div
                    ref={(menuButton) => { this.menuButton = menuButton; }}
                    className="ag-icon ag-icon-menu"
                    onClick={this.onMenuClicked.bind(this)}>&nbsp;</div>}
                <div className="customHeaderLabel">{this.props.displayName}</div>
            </div>
        );
    }

    onMenuClicked() {
        this.props.showColumnMenu(this.menuButton);
    }
}

// grid-packages/ag-grid-docs/new/src/pages/column-updating-definitions/examples/refresh-headers/_gen/modules/angular/app/custom-header.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';

@Component({
  selector: 'app-loading-overlay',
  template: `
    <div style="display: flex">
      <span
        *ngIf="params.enableMenu"
        #menuButton
        class="ag-icon ag-icon-menu"
        (click)="onMenuClicked($event)"
      ></span>
      <div style="flex-grow: 1;">
        <span ref="eText">{{ params.displayName }}</span>
      </div>
    </div>
  `,
})
export class CustomHeader {
  private params: any;

  @ViewChild('menuButton', { read: ElementRef }) public menuButton;

  agInit(params): void {
    this.params = params;
  }

  refresh(params): boolean {
    this.params = params;
    return true;
  }

  onMenuClicked() {
    this.params.showColumnMenu(this.menuButton.nativeElement);
  }
}
