// src/ng2-example/app/header-group-component/header-group.component.ts
import {Component} from "@angular/core";
import {IHeaderGroupParams} from "ag-grid/main";
import {IHeaderGroupAngularComp} from "ag-grid-angular/main";

@Component({
    moduleId: module.id,
    templateUrl: 'header-group.component.html',
    styleUrls: ['header-group.component.css']
})
export class HeaderGroupComponent implements IHeaderGroupAngularComp {
    public params: IHeaderGroupParams;
    public expanded: boolean;

    agInit(params: IHeaderGroupParams): void {
        this.params = params;
        this.params.columnGroup.getOriginalColumnGroup().addEventListener('expandedChanged', this.onExpandChanged.bind(this));
    }

    ngOnDestroy() {
        console.log(`Destroying HeaderComponent`);
    }


    expandOrCollapse() {
        this.params.setExpanded(!this.expanded);
    };

    onExpandChanged() {
        this.expanded = this.params.columnGroup.getOriginalColumnGroup().isExpanded()
    }
}
<div>
    <div class="customHeaderLabel"> {{this.params.displayName}}</div>
    <div (click)="expandOrCollapse()" class="{{'customExpandButton' + (this.expanded ?  ' expanded': ' collapsed')}}"><i class="fa fa-arrow-right" ></i></div>
</div>

// packages/ag-grid-docs/src/react-more-details/full-rich-markup/HeaderGroupComponent.jsx
import React from 'react';
import * as PropTypes from 'prop-types';

// Header component to be used as default for all the columns.
export default class HeaderGroupComponent extends React.Component {

    constructor(props) {
        super(props);
        this.props.columnGroup.getOriginalColumnGroup().addEventListener('expandedChanged', this.onExpandChanged.bind(this));
        this.state = {
            expanded: null
        };
    }

    componentDidMount() {
        this.onExpandChanged();
    }

    render() {
        let arrowClassName = "customExpandButton " + (this.state.expanded ? " expanded" : " collapsed");

        return <div>
            <div className="customHeaderLabel"> {this.props.displayName}</div>
            <div onClick={this.expandOrCollapse.bind(this)} className={arrowClassName}><i
                className="fa fa-arrow-right"/></div>
        </div>
    }

    expandOrCollapse() {
        this.props.setExpanded(!this.state.expanded);
    };

    onExpandChanged() {
        this.setState({
            expanded: this.props.columnGroup.getOriginalColumnGroup().isExpanded()
        })
    }
}

// the grid will always pass in one props called 'params',
// which is the grid passing you the params for the cellRenderer.
// this piece is optional. the grid will always pass the 'params'
// props, so little need for adding this validation meta-data.
HeaderGroupComponent.propTypes = {
    params: PropTypes.object
};
