// src/angular-examples/app/editor-component-example/mood-editor.component.ts
import {AfterViewInit, Component, ViewChild, ViewContainerRef} from "@angular/core";

import {ICellEditorAngularComp} from "ag-grid-angular/main";

@Component({
    selector: 'editor-cell',
    template: `
        <div #container class="mood" tabindex="0" (keydown)="onKeyDown($event)">
            <img src="images/smiley.png" (click)="onClick(true)" [ngClass]="{'selected' : happy, 'default' : !happy}">
            <img src="images/smiley-sad.png" (click)="onClick(false)"
                 [ngClass]="{'selected' : !happy, 'default' : happy}">
        </div>
    `,
    styles: [`
        .mood {
            border-radius: 15px;
            border: 1px solid grey;
            background: #e6e6e6;
            padding: 15px;
            text-align: center;
            display: inline-block;
            outline: none
        }

        .default {
            padding-left: 10px;
            padding-right: 10px;
            border: 1px solid transparent;
            padding: 4px;
        }

        .selected {
            padding-left: 10px;
            padding-right: 10px;
            border: 1px solid lightgreen;
            padding: 4px;
        }
    `]
})
export class MoodEditorComponent implements ICellEditorAngularComp, AfterViewInit {
    private params: any;

    @ViewChild('container', {read: ViewContainerRef}) public container;
    public happy: boolean = false;

    // dont use afterGuiAttached for post gui events - hook into ngAfterViewInit instead for this
    ngAfterViewInit() {
        this.container.element.nativeElement.focus();
    }

    agInit(params: any): void {
        this.params = params;
        this.setHappy(params.value === "Happy");
    }

    getValue(): any {
        return this.happy ? "Happy" : "Sad";
    }

    isPopup(): boolean {
        return true;
    }

    setHappy(happy: boolean): void {
        this.happy = happy;
    }

    toggleMood(): void {
        this.setHappy(!this.happy);
    }

    onClick(happy: boolean) {
        this.setHappy(happy);
        this.params.api.stopEditing();
    }

    onKeyDown(event): void {
        let key = event.which || event.keyCode;
        if (key == 37 ||  // left
            key == 39) {  // right
            this.toggleMood();
            event.stopPropagation();
        }
    }
}

// src/vue-examples/src/editor-component-example/MoodEditorComponent.vue
<template>
    <div :ref="'container'" class="mood" tabindex="0" @keydown="onKeyDown">
        <img src="images/smiley.png" @click="onClick(true)" :class="{selected : happy, default : !happy}">
        <img src="images/smiley-sad.png" @click="onClick(false)" :class="{selected : !happy, default : happy}">
    </div>
</template>

<script>
    import Vue from "vue";

    export default Vue.extend({
        data() {
            return {
                happy: false,
                imgForMood: null
            }
        },
        methods: {
            getValue() {
                return this.happy ? "Happy" : "Sad";
            },

            isPopup() {
                return true;
            },

            setHappy(happy) {
                this.happy = happy;
            },

            toggleMood() {
                this.setHappy(!this.happy);
            },

            onClick(happy) {
                this.setHappy(happy);
                this.params.api.stopEditing();
            },

            onKeyDown(event) {
                let key = event.which || event.keyCode;
                if (key == 37 ||  // left
                    key == 39) {  // right
                    this.toggleMood();
                    event.stopPropagation();
                }
            }
        },
        created() {
            this.setHappy(this.params.value === "Happy");
        },
        mounted() {
            Vue.nextTick(() => {
                this.$refs.container.focus();
            });
        }
    })
</script>


<style scoped>
    .mood {
        border-radius: 15px;
        border: 1px solid grey;
        background: #e6e6e6;
        padding: 15px;
        text-align: center;
        display: inline-block;
        outline: none
    }

    .default {
        border: 1px solid transparent !important;
        padding: 4px;
    }

    .selected {
        border: 1px solid lightgreen !important;
        padding: 4px;
    }
</style>
