// src/example-angular-editor/editor/app/mood-renderer.component.ts
import {Component} from "@angular/core";

import {ICellRendererAngularComp} from "ag-grid-angular";

@Component({
    selector: 'mood-cell',
    template: `<img width="20px" [src]="imgForMood"/>`
})
export class MoodRendererComponent implements ICellRendererAngularComp {
    private params: any;
    private mood: string;
    public imgForMood: string;

    agInit(params: any): void {
        this.params = params;
        this.setMood(params);
    }

    refresh(params: any): boolean {
        this.params = params;
        this.setMood(params);
        return true;
    }

    private setMood(params) {
        this.mood = params.value;
        this.imgForMood = this.mood === 'Happy' ? '/images/smiley.png' : '/images/smiley-sad.png';
    };
}

// src/javascript-grid-cell-editor/react-editor/MoodRenderer.jsx
import React, {Component} from "react";

export default class MoodRenderer extends Component {
    constructor(props) {
        super(props);
    }

    componentWillMount() {
        this.setMood(this.props.value)
    }

    refresh(params) {
        this.setMood(params.value);
    }

    setMood(mood) {
        this.setState({
            imgForMood: mood === 'Happy' ? '/images/smiley.png' : '/images/smiley-sad.png'
        })
    };

    render() {
        return (
            <img width="20px" src={this.state.imgForMood}/>
        );
    }
}
