// grid-community-modules/solid/src/index.tsx
import AgGridSolid from "./grid/agGridSolid";
export default AgGridSolid;

export * from "./grid/agGridSolid";

// /* @refresh reload */
// import { render } from 'solid-js/web';
//
// import './index.css';
// import App from './sampleApp/App';
//
// render(() => <App />, document.getElementById('root') as HTMLElement);

// documentation/ag-grid-docs/scripts/showcase-github/examples/ag-grid-showcase-example-vite-react/src/main.tsx
import React from 'react';
import ReactDOM from 'react-dom/client';

import PortfolioExample from './components/portfolio-example/portfolio-example';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
    <React.StrictMode>
        <PortfolioExample />
    </React.StrictMode>
);
